apiVersion: v1
kind: ClusterRole
metadata:
  name: system:node-problem-detector
rules:
- apiGroups:
  - ""
  attributeRestrictions: null
  resources:
  - nodes
  - nodes/status
  verbs:
  - patch
- apiGroups:
  - ""
  attributeRestrictions: null
  resources:
  - nodes
  - pods
  verbs:
  - get

