kind: SecurityContextConstraints
apiVersion: v1
metadata:
  name: npd
allowPrivilegedContainer: true
allowHostDirVolumePlugin: true
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
users:
- system:serviceaccount:default:node-problem-detector-sa

