apiVersion: v1
kind: ClusterRoleBinding
metadata:
  name: system:node-problem-detector
  namespace: default
userNames:
- system:serviceaccount:default:node-problem-detector-sa
subjects:
- kind: ServiceAccount
  name: node-problem-detector-sa
  namespace: default
roleRef:
  name: system:node-problem-detector
